version: '3'
services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper:latest
    restart: always
    ports:
      - "2181:2181"
    networks:
      - ki-net
    volumes:
      - ./kafka_data/zookeeper-data:/var/lib/zookeeper/data
      - ./kafka_data/zookeeper-log:/var/lib/zookeeper/log
  # kafka 客户端脚本在 /opt/ 目录下 -------------------------------------------
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME:  127.0.0.1
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      # KAFKA_CREATE_TOPICS: "test:1:1,sdk:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./kafka_data:/kafka
    networks:
      - fa-net
networks:
  ki-net:
    external: true